version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: entry_service_db
    environment:
      POSTGRES_DB: entry_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres
      -c max_connections=500
      -c shared_buffers=2GB
      -c effective_cache_size=4GB
      -c work_mem=32MB
      -c maintenance_work_mem=1GB
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d entry_service"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: